version: '3.8'
services:
  icough-front:
    build:
      context: ./icough-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_IP=
    image: icough-front:latest
    ports:
      - "4444:3000"
    restart: always
    container_name: icough-front

  icough-back:
    build:
      context: ./icough-back
      dockerfile: Dockerfile
    image: icough-back:latest
    ports:
      - "8888:8000"
    restart: always
    environment:
      - MONGO_CONNECTION_STRING=
    container_name: icough-back

